name: Nightly Documentation Update

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so quote this string
    - cron:  '0 1 * * *'

jobs:
  # Run the common workflow on each pull request
  Nightly_Documentation_Update:
    uses: 51Degrees/common-ci/.github/workflows/nightly-documentation-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
