name: Nightly Pipeline

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false
  schedule:
    - cron: '0 2 * * *'

jobs:
  PackageUpdate:
    name: Nightly Package Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  SubmoduleUpdate:
    name: Nightly Submodule Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-submodule-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  PullRequests:
    if: ${{ !cancelled() }}
    needs: [PackageUpdate, SubmoduleUpdate]
    name: Nightly Pull Requests
    uses: 51Degrees/common-ci/.github/workflows/nightly-pull-requests.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
      NginxKey: ${{ secrets.NGINX_PLUS_KEY }}
      NginxCert: ${{ secrets.NGINX_PLUS_CERT }}
      NginxJwtToken: ${{ secrets.NGINX_PLUS_JWT_TOKEN }}

  Publish:
    if: ${{ !cancelled() }}
    needs: PullRequests
    name: Nightly Publish
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
      NginxKey: ${{ secrets.NGINX_PLUS_KEY }}
      NginxCert: ${{ secrets.NGINX_PLUS_CERT }}
      NginxJwtToken: ${{ secrets.NGINX_PLUS_JWT_TOKEN }}
